[package]
name = "GBR"
version = "0.1.0"
authors = ["Noboru Horita <61climb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
bitflags = "1.2.1"